file_name_dict = {"drug_file_name": "CTRP_AAC_MORGAN.hdf",
                  "pretrain_exp_file_name": "TCGA_PreTraining_Expression.hdf",
                  "pretrain_cnv_file_name": "TCGA_PreTraining_CopyNumber.hdf",
                  "depmap_mut_file_name": "DepMap_21Q2_Mutations_by_Cell.hdf",
                  "depmap_cnv_file_name": "DepMap_21Q2_CopyNumber.hdf",
                  "depmap_exp_file_name": "DepMap_21Q2_Expression.hdf",
                  "depmap_prot_file_name": "DepMap_20Q2_No_NA_ProteinQuant.hdf",
                  "depmap_mirna_file_name": "DepMap_2019_miRNA.hdf",
                  "depmap_hist_file_name": "DepMap_2019_ChromatinProfiling.hdf",
                  "depmap_rppa_file_name": "DepMap_2019_RPPA.hdf",
                  "depmap_metab_file_name": "DepMap_2019_Metabolomics.hdf",

                  "gdsc_mut_file_name": "DepMap_21Q2_Mutations_by_Cell.hdf",
                  "gdsc_cnv_file_name": "DepMap_21Q2_CopyNumber.hdf",
                  # "gdsc_exp_file_name": "GDSC_Training_Expression.hdf",
                  "gdsc_exp_file_name": "DepMap_21Q2_Expression.hdf",

                  "gdsc_prot_file_name": "DepMap_20Q2_No_NA_ProteinQuant.hdf",
                  "gdsc_mirna_file_name": "DepMap_2019_miRNA.hdf",
                  "gdsc_hist_file_name": "DepMap_2019_ChromatinProfiling.hdf",
                  "gdsc_rppa_file_name": "DepMap_2019_RPPA.hdf",
                  "gdsc_metab_file_name": "DepMap_2019_Metabolomics.hdf",

                  "tum_file_name": "DepMap_21Q2_Line_Info.csv",
                  "gdsc1_file_name": "GDSC1_AAC_MORGAN.hdf",
                  "gdsc2_file_name": "GDSC2_AAC_MORGAN.hdf",
                  "pretrain_exp_embed_file_name": "optimal_autoencoders/EXP_pretrain_Omic_AutoEncoder_Checkpoint.pt",
                  "pretrain_cnv_embed_file_name": "optimal_autoencoders/CNV_pretrain_Omic_AutoEncoder_Checkpoint.pt",
                  "mut_embed_file_name": "optimal_autoencoders/MUT_Omic_AutoEncoder_Checkpoint.pt",
                  "cnv_embed_file_name": "optimal_autoencoders/CNV_Omic_AutoEncoder_Checkpoint.pt",
                  "exp_embed_file_name": "optimal_autoencoders/EXP_Omic_AutoEncoder_Checkpoint.pt",
                  "prot_embed_file_name": "optimal_autoencoders/PROT_Omic_AutoEncoder_Checkpoint.pt",
                  "mirna_embed_file_name": "optimal_autoencoders/MIRNA_Omic_AutoEncoder_Checkpoint.pt",
                  "hist_embed_file_name": "optimal_autoencoders/HIST_Omic_AutoEncoder_Checkpoint.pt",
                  "rppa_embed_file_name": "optimal_autoencoders/RPPA_Omic_AutoEncoder_Checkpoint.pt",
                  "metab_embed_file_name": "optimal_autoencoders/METAB_Omic_AutoEncoder_Checkpoint.pt",
                  "GlobalCodeSize_512_mut_embed_file_name": "optimal_autoencoders/MUT_GlobalCodeSize_512_Omic_AutoEncoder_Checkpoint.pt",
                  "GlobalCodeSize_512_cnv_embed_file_name": "optimal_autoencoders/CNV_GlobalCodeSize_512_Omic_AutoEncoder_Checkpoint.pt",
                  "GlobalCodeSize_512_exp_embed_file_name": "optimal_autoencoders/EXP_GlobalCodeSize_512_Omic_AutoEncoder_Checkpoint.pt",
                  "GlobalCodeSize_512_prot_embed_file_name": "optimal_autoencoders/PROT_GlobalCodeSize_512_Omic_AutoEncoder_Checkpoint.pt",
                  "GlobalCodeSize_512_mirna_embed_file_name": "optimal_autoencoders/MIRNA_GlobalCodeSize_512_Omic_AutoEncoder_Checkpoint.pt",
                  "GlobalCodeSize_512_hist_embed_file_name": "optimal_autoencoders/HIST_GlobalCodeSize_512_Omic_AutoEncoder_Checkpoint.pt",
                  "GlobalCodeSize_512_rppa_embed_file_name": "optimal_autoencoders/RPPA_GlobalCodeSize_512_Omic_AutoEncoder_Checkpoint.pt",
                  "GlobalCodeSize_512_metab_embed_file_name": "optimal_autoencoders/METAB_GlobalCodeSize_512_Omic_AutoEncoder_Checkpoint.pt",
                  "4096_drug_embed_file_name": "optimal_autoencoders/Morgan_4096_AutoEncoder_Checkpoint.pt",
                  "2048_drug_embed_file_name": "optimal_autoencoders/Morgan_2048_AutoEncoder_Checkpoint.pt",
                  "1024_drug_embed_file_name": "optimal_autoencoders/Morgan_1024_AutoEncoder_Checkpoint.pt",
                  "512_drug_embed_file_name": "optimal_autoencoders/Morgan_512_AutoEncoder_Checkpoint.pt"
                  }
